### ISSUE TITLE
Can’t establish a connection to the server at ws://localhost:3300/wpilibws.

### ISSUE THREAD

**Issue by KenwoodFox** [frc-web-components/frc-web-components#130]
I know its pretty quiet here so im mostly just documenting this issue for the pourposes of tracking but, ive got the components setup and they seem to work pretty well, im pleased but it looks like i keep getting this error here, and my dashboard takes about 15 seconds to "connect", connecting to nt once i get this first error.

![image](https://user-images.githubusercontent.com/31870999/214694508-ed624fd8-84b3-4121-b525-df668ff1702f.png)

I cant exactly tell what its looking for, i already had my own pynetworktables2js setup so maybe they're conflicting but this is built into the latest release so im not sure. 

```js
  setAddress(address) {
    if (address === 'gitpod') {
      Object(_socket__WEBPACK_IMPORTED_MODULE_1__["connect"])("wss://3300".concat(window.location.href.substring(12), "wpilibws"));
    } else {
      Object(_socket__WEBPACK_IMPORTED_MODULE_1__["connect"])("ws://".concat(address, ":3300/wpilibws"));
    }
  }
```

**Comment by KenwoodFox** [comment]
Is wpilibws the dashboard?

![image](https://user-images.githubusercontent.com/31870999/214771043-75dcbb6d-d318-4557-868b-573a8c6f2ee0.png)
Heres what the delay looks like for the webserver, like exactly 10 seconds

**Comment by KenwoodFox** [comment]
Is this maybe part of halsim? Is there a way to disable it? Looks like portions of the final code appear here: https://github.com/frc-web-components/frc-web-components/blob/master/src/source-providers/halsim/index.js#L56-L62

**Comment by amorygalili** [comment]
Hi @KenwoodFox, it is indeed for the halsim. As for your NT issues, I believe your best bet is to actually use the newer version of FRC Web Components which is in this branch: https://github.com/frc-web-components/frc-web-components/tree/version4

I'm still working on documentation and squashing some bugs so it's not 100% ready, but my team plans on using it for this season. It makes use of NT4 so pynetworktables2js is no longer needed. My recommendation is to try out that version since you will be much more likely to receive support for issues that you're having. If you do try it and run into any issues with it or questions feel free to post them here and I'll respond to them as quickly as I can.

**Comment by KenwoodFox** [comment]
> Hi @KenwoodFox, it is indeed for the halsim. As for your NT issues, I believe your best bet is to actually use the newer version of FRC Web Components which is in this branch: [`version4`](https://github.com/frc-web-components/frc-web-components/tree/version4?rgh-link-date=2023-01-27T21%3A07%3A39Z) The new version doesn't currently support the halsim stuff so you won't see those errors either.
> 
> I'm still working on documentation and squashing some bugs so it's not 100% ready, but my team plans on using it for this season. It makes use of NT4 so pynetworktables2js is no longer needed. My recommendation is to try out that version since you will be much more likely to receive support for issues that you're having. If you do try it and run into any issues with it or have questions feel free to post them here and I'll respond to them as quickly as I can.

Thanks so much for the reply! Ill give it a go and see what we can do! My team so far finds more comfort just implementing pynt themselves so maybe i can convince them to pivot and provide their custom widgets back to your new branch, fingers crossed!

**Comment by amorygalili** [comment]
That works as well. Feel free to also share your code and I can help get you started if you'd like to migrate. I'm interested in getting feedback so it would help me out too.
