### ISSUE TITLE
Add documentation to make the application easier to use

### ISSUE THREAD

**Issue by 26grogab** [frc-web-components/frc-web-components#131]
I have been pulling my hair out for several weeks now trying to figure out how to use this dashboard, but everything I have tried is not working. The problems that I am running into are:
- When connecting the dashboard to pynetworktables at localhost:8888, all I get is a blank screen, when running it through vite at any other port seems to work fine
- `tsconfig.node.json`  is looking for `vite.config.ts`, when the actual file is `vite.config.js`
- I do not know how to connect it to a robot

If you could provide documentation on any of this and how to run it, build it, and use it, that would be amazing.
Thanks!

**Comment by 26grogab** [comment]
Just to clarify, I am having problems with the `version4` branch.

**Comment by amorygalili** [comment]
Hi @26grogab sorry to hear about the issues you're having. The `version4` branch uses NT4 so `pynetworktables2js` is no longer a dependency. You should be able to connect to the robot without it. Also, are you running it by pulling down the code and running it with `npm start`? I wouldn't recommend running the dashboard that way. There's a tauri app you can download from here: https://github.com/frc-web-components/app/releases. There's also a doc going over the dashboard interface: https://github.com/frc-web-components/frc-web-components/blob/version4/docs/dashboard.rst. Apologies for the state of the docs. They're still very much in progress. Let me know if you have specific suggestions on improvements you'd like to see.

**Comment by 26grogab** [comment]
Hello! Thanks for all of the info on networktables and using npm to start it, as that has resolved a couple of issues! I have tried using the tauri app, but after connecting to `localhost:8888` under settings with networktables running, all I get is a blank page, as detailed in the image.
![image_2023-02-12_213750413](https://user-images.githubusercontent.com/37960760/218364844-85878348-4e09-4387-a366-c6da2935de00.png)
Even after reinstalling the application, and always using the newest version, I always get the same thing. Do you have any insight on what might be happening?

Also, how would I use NT4 in your program. I did not figure out how to do that. Thanks for your help, and I really appreciate it!

**Comment by amorygalili** [comment]
Is `localhost:8888` the pynetworktables2js server? When you say "after connecting to localhost:8888", does the app show only when you run the server or does that happen even when you don't? NT4 doesn't require anything special to run. You just need outlineviewer running in server mode, the robot code running in simulation, or a running robot:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/6786620/218368391-e9b674ce-d0ae-4bcc-9552-84bdd95c5d8d.png">

You'll want the `NT4` to be localhost if running the server locally in outlineviewer or in simulation, or the IP address of your robot (usually 10.TE.AM.2). I'm not sure about the issues you're having with the blank screen. Are you running the app on linux? I have not done a lot of testing on linux machines so I'm not sure what issues you might be running into. Could you open up devtools and post a screenshot of errors you see in the console?

<img width="535" alt="image" src="https://user-images.githubusercontent.com/6786620/218369070-48de847e-8b4d-4272-afa9-e540bcf607b2.png">

I'm able to access it by right clicking the app (to open the context menu) and then clicking inspect:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/6786620/218368643-29c16a8b-8f3f-4b9f-904c-778d8b929bd4.png">

**Comment by 26grogab** [comment]
Yes, `localhost:8888` is pynetworktables's server, as the app shows a blank page right away on app startup. I am running Windows 11 if that matters. Here are the errors that I see:
![Screenshot_20230213_083719](https://user-images.githubusercontent.com/37960760/218624581-5d9c5f62-0993-4026-8fb1-0459632d202c.png)

Also, I have a couple more questions/problems:
- Should I use NPM to install all packages under `package.json`?
- I do not see an option to use `npm run` anywhere. I was using vite to start it when I said that some issues were resolved. Can you show me where to go for that? I can't see the dashboard or any of it's options anymore.
Again, thank you so much for all of your help!

**Comment by amorygalili** [comment]
I think I see your issue now. So you should actually not add a port in the `NT4 Server` input field. It should just be left as `localhost`. pynetworktables is no longer used with the dashboard and you should be able to connect to your robot/simulation/outlineviewer without it. I was able to reproduce your issue and you can solve it like this:

![FRC_Web_Components_0o5eIRlNwL](https://user-images.githubusercontent.com/6786620/218652342-c03684e5-07c2-4ee5-a0e8-b4bd23e58713.gif)

As for running the app, I would recommend installing it instead of building it yourself unless you plan on developing/modifying it. You can download it from the releases page here: https://github.com/frc-web-components/app/releases:

![AROHwa443J](https://user-images.githubusercontent.com/6786620/218653961-4babd678-d936-4701-bc82-e3999a6c08da.gif)

**Comment by 26grogab** [comment]
After doing all of these steps, I can get the dashboard to show up, and get connected to the robot, but I can't get it to receive any input from the robot. I have the NT4 setting set to 10.22.2.2 (our team number is 2202), and I messed around with OutlineViewer a bit, but I can't get any input from the robot. Here are the errors that I get when connected to the robot IP:
![Screenshot_20230215_070640](https://user-images.githubusercontent.com/37960760/219231747-b962ca88-cd87-4654-9c9e-385a3201dec2.png)
Any input on this?

**Comment by amorygalili** [comment]
@26grogab could you try this release and see if you get the same error? https://github.com/frc-web-components/app/releases/tag/app-v0.1.4

**Comment by 26grogab** [comment]
Sorry for the late response, I didn't have a robot that I could use. Everything works perfectly fine, and I can see values from the robot. Thanks for all of your help!
