### ISSUE TITLE
Accelerometer framework

### ISSUE THREAD

**Issue by 26grogab** [frc-web-components/frc-web-components#150]
I'm currently working on a plugin to calculate acceleration automatically by taking the current value, subtracting the previous value, and dividing by time, since we don't have an acceleration NT value. I followed the plugin tutorial and got everything setup, but I failed to find the base Web Components framework for the accelerometer, which I need for the plugin. 
Are you able to provide that for me? Thanks!
Ben

**Comment by amorygalili** [comment]
Hi Ben, are you trying to include the component inside another custom component? You could do that by including `frc-accelerometer` element into your custom element's html. For example:

```<frc-accelerometer value=".9" min="0"></frc-accelerometer>```

More examples can be found here:

**Comment by 26grogab** [comment]
Thanks! I appreciate it.
