### ISSUE TITLE
network tables do not automatically update

### ISSUE THREAD

**Issue by nickquednow** [frc-web-components/frc-web-components#23]
The current solution for updating values is to write your own javascript to update values, but I feel that it would be better to go ahead and add this javascript at the very top of the source to automatically listen and change values.

An example of a solution (in javascript):
```
//this code here is so that there is fewer DOM calls for performance reasons
var dom-array = document.querySelectorAll("[key]");
var dom-key-values = []; //used in the global listener so the listener does not have to recompute the name of the element every call
var current-dom-tag = 0; //the index number of the dom array avriable
var dom-array-length = dom-array.length - 1; //put here so the while loop does not have to keep recomputing the length
while(current-dom-tag < dom-array-length){
    dom-key-values[current-dom-tag] = dom-array[current-dom-tag].getAttribute('key');
}
NetworkTables.addGlobalListener(function (key, value, isNew) {
    var key_value;
    if (key.toString().substr(0, 15) === "/SmartDashboard") {
        key_value = key.toString().substr(15);
    } else {
        key_value = key.toString();
    }
    if (!(key_value === "/dsTime" || key_value === "/robotTime")) {
        dom-array[dom-key-values.findIndex(function(arr){return arr == key_value})].value = value.toString();
   }
}, true);
```

or if you wanted this behavior in the first place, maybe an attribute of "auto-update"
code:
```
//this code here is so that there is fewer DOM calls for performance reasons
var dom-array = document.querySelectorAll("[auto-update='true']");
var dom-key-values = []; //used in the global listener so the listener does not have to recompute the name of the element every call
var current-dom-tag = 0; //the index number of the dom array avriable
var dom-array-length = dom-array.length - 1; //put here so the while loop does not have to keep recomputing the length
while(current-dom-tag < dom-array-length){
    dom-key-values[current-dom-tag] = dom-array[current-dom-tag].getAttribute('key');
}
NetworkTables.addGlobalListener(function (key, value, isNew) {
    var key_value;
    if (key.toString().substr(0, 15) === "/SmartDashboard") {
        key_value = key.toString().substr(15);
    } else {
        key_value = key.toString();
    }
    if (!(key_value === "/dsTime" || key_value === "/robotTime")) {
        dom-array[dom-key-values.findIndex(function(arr){return arr == key_value})].value = value.toString();
   }
}, true);
```

I would love to contribute as well, but what libraries are you using for the HTML elements, so I can look at the documentation and inform myself of the library before contributing.

**Comment by amorygalili** [comment]
Hi @nickquednow , thank you for opening up an issue and for offering to contribute! There's a lot of work to be done, and any help or feedback is much appreciated. The library I'm using to create the components is [LitElement](https://lit-element.polymer-project.org/), so I would start there. They have pretty good live examples and their guide covers it pretty well.

The feature you mentioned (unless I've misunderstood) is actually already built into the components. You can actually connect NetworkTables to your components and auto-update them without writing any javascript at all. You do this by adding the "source-key" attribute to the component, and setting it equal to the NetworkTable subtable or key you want to use to provide data to your component. Take the [voltage view](https://frc-web-components.github.io/components/voltage-view/) component for example:

You can write this code to set some of the attributes:

`<frc-voltage-view value="3.5" precision="2"></frc-voltage-view>`

And you'll be presented with this:

![Screen Shot 2020-06-06 at 12 43 00 PM](https://user-images.githubusercontent.com/6786620/83949686-4bdeb700-a7f3-11ea-889a-f1b2817165e6.png)

However, you can override the attribute values by adding a source-key attribute for an existing NetworkTable key:

`<frc-voltage-view source-key="/SmartDashboard/voltage" value="3.5" precision="2"></frc-voltage-view>`

If the key is an existing single entry in NetworkTables, its value will be used to set the component's _primary_ attribute (in this case the primary attribute is value). If the value of "/SmartDashboard/voltage" is 5 for example, you'll be presented with this:

![Screen Shot 2020-06-06 at 12 48 38 PM](https://user-images.githubusercontent.com/6786620/83949845-11294e80-a7f4-11ea-97a0-97628f4e7a9e.png)

If you provide a key that's an existing NetworkTable subtable, it will take the subtable's keys and map them to the attributes in the component. For example. If you have the following NetworkTable key value pairs:

"/voltageView/value" = 4.546
"/voltageView/unit" = "Volts"

and you have the following HTML:

`<frc-voltage-view source-key="/voltageView" value="3.5" precision="2"></frc-voltage-view>`

You will be presented with this:

![Screen Shot 2020-06-06 at 12 53 22 PM](https://user-images.githubusercontent.com/6786620/83949913-bb08db00-a7f4-11ea-9a45-52aeebc7600d.png)

No javascript is necessary here, and the attribute values will automatically change when the NetworkTable values change. Likewise for interactive components such as the [toggle switch](https://frc-web-components.github.io/components/toggle-switch/) component, they automatically update the values in NetworkTables when they are updated by the user.

**Comment by nickquednow** [comment]
My problem was apparently the lack of me being able to read my own code XD. In the python files that gave random values to the network table entries, I have "SmartDashboard as the parent table by default so in the python file it puts all of the entries there and I failed to reflect that in the HTML file.

But hopefully, during the free time that I will have this summer, I hope to be able to contribute to this repository and, hopefully, we can get it ready for the 2021 season.
