### ISSUE TITLE
Gyro component should have properties to match Rotation2d

### ISSUE THREAD

**Issue by shueja-personal** [frc-web-components/frc-web-components#95]
It's probably fine to display it in degrees, but often when using odometry, we (6995) are retrieving our gyro and pose data in radians, and logging it as such, so right now the FWC gyro is showing -3.14 degrees to 3.14 degrees. I imagine the usage would just look like
```html
<frc-gyro source-key="/poseHeading" precision="2" useRadians="true"></frc-gyro>
```
And to minimize code refactoring, the JS component would multiply the source value by 180/pi if useRadians is true.
Is this within scope?

EDIT: On further testing, it seems like it might be better to have a separate but similar option for counting CCW positive, to match the WPILib geometry classes.

**Comment by amorygalili** [comment]
@shueja-personal How does this look?

<img width="593" alt="gyro-radians" src="https://user-images.githubusercontent.com/6786620/210129444-ac3ea6c1-26dc-4977-80cf-62f18ec74370.png">
<img width="605" alt="gyro-ccw" src="https://user-images.githubusercontent.com/6786620/210129447-da2a4b99-1ba4-4e75-a7dd-32ad81e15fc7.png">
